Update baixador_de_repo
Alterado nomes de usuário e repositório e adicionado mais coisas. Explicações em breve.

diff --git a/baixador_de_repo b/baixador_de_repo
--- a/baixador_de_repo
+++ b/baixador_de_repo
@@ -1,14 +1,34 @@
 #!/bin/bash
 
 # Definir o nome do usuário e o nome do repositório a duas variavéis no codigo
-username="SheepN0tF0und"   # Altere aqui o nome do dono do repositório que onde deseja baixar o repositório
-reponame="InstaladorTDI"   # Altere aqui o nome do repositorio que deseja baixar
+username="Sans01hp"   # Altere aqui o nome do dono do repositório que onde deseja baixar o repositório
+reponame="testes_shellscript"   # Altere aqui o nome do repositorio que deseja baixar
 
 
 # Faz a verificação se esse diretorio/repositório ja existe.
 if [ -d "$reponame" ]; then
-    echo -e "\e[92mRepositório requerido já instalado.\e[0m"
-  else 
+    echo -e "\e[92mRepositório já instalado.\e[0m"
+echo -e "deseja instalar a versão mais recente?(y/n)"
+
+read escolha #variavel "escolha" irá armazenar a resposta (y/n) para comparar com o bloco case
+case $escolha in 
+y|Y) 
+     cd ~/$reponame
+     git reset --hard 
+     git pull
+     ;;
+n|N) 
+     echo -e "instalação cancelada"    
+     exit 0
+     ;;
+*)
+     echo -e "operação invalida, saindo..."
+     exit 1
+     ;;
+esac
+    
+
+else 
 
 # Clonar o repositório
       git clone https://github.com/$username/$reponame
